### ISSUE TITLE
Error on Mac

### ISSUE THREAD

**Issue by matteocourthoud** [frogstack/HSTeamPlay#2]
Hello!

I am having the following error on Mac when I run HSTeamPlay:

WARNING: Couldn't load rating data. Starting with a new database. The error was: open ratingsDB.json: no such file or directory
WARNING: Couldn't load game history. Starting a new log. The error was: open gameDB.json: no such file or directory
panic: open Applications/Hearthstone/Logs/Power.log: no such file or directory

I have the Log file in the correct place but it seems unable to find it.

Matteo

**Comment by matteocourthoud** [comment]
Ok, problem solved, it was just a slash in the path. I should have signaled it (I am not very familiar with github so please tell me if I did something wrong).

**Comment by frogstack** [comment]
I can't test this on a mac so I'm assuming your thing works and merged it. Thanks for the PR!
