### ISSUE TITLE
Update for Knights of the Frozen Throne

### ISSUE THREAD

**Issue by ghost** [frogstack/HSTeamPlay#5]
Hello, so hsteamplay doesnt recognize the cards from the Knights of the Frozen Throne, would be much appreciated if it got an update, thanks!

**Comment by matteocourthoud** [comment]
I just pulled a request to update the card database!

**Comment by frogstack** [comment]
Honestly I had no idea people were using this, so I was taking my time with it. I've merged @matteocourthoud's update and it should now be working for KFT.
